export const ErrorExceptionType = {
  // Generic
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  SERVER_ERROR: 'SERVER_ERROR',
  CLIENT_ERROR: 'CLIENT_ERROR',

  // Student
  INVALID_STUDENT_ID: 'INVALID_STUDENT_ID',
  MISSING_STUDENT_ID: 'MISSING_STUDENT_ID',
  STUDENT_NOT_FOUND: 'STUDENT_NOT_FOUND',
  STUDENT_ALREADY_ENROLLED: 'STUDENT_ALREADY_ENROLLED',
  STUDENT_ASSIGNMENT_NOT_FOUND: 'STUDENT_ASSIGNMENT_NOT_FOUND',

  // Class
  INVALID_CLASS_ID: 'INVALID_CLASS_ID',
  MISSING_CLASS_ID: 'MISSING_CLASS_ID',
  CLASS_NOT_FOUND: 'CLASS_NOT_FOUND',

  // Assignment
  INVALID_ASSIGNMENT_ID: 'INVALID_ASSIGNMENT_ID',
  MISSING_ASSIGNMENT_ID: 'MISSING_ASSIGNMENT_ID',
  ASSIGNMENT_NOT_FOUND: 'ASSIGNMENT_NOT_FOUND',
} as const;
